// Seed vocabulary: intermediate–advanced Korean.
// Fields: ko (Korean), en (English meaning), ex (Korean example), exEn (translation), topic.
export const SEED = [
  // ── Everyday / news & society ──
  { ko: "현상", en: "phenomenon", ex: "이 현상은 전 세계적으로 나타나고 있다.", exEn: "This phenomenon is appearing worldwide.", topic: "society" },
  { ko: "추세", en: "trend", ex: "출산율 감소 추세가 이어지고 있다.", exEn: "The declining birthrate trend continues.", topic: "society" },
  { ko: "격차", en: "gap; disparity", ex: "빈부 격차가 점점 커지고 있다.", exEn: "The wealth gap is widening.", topic: "society" },
  { ko: "논란", en: "controversy", ex: "그 발언은 큰 논란을 일으켰다.", exEn: "The remark sparked a huge controversy.", topic: "society" },
  { ko: "여론", en: "public opinion", ex: "여론이 빠르게 바뀌었다.", exEn: "Public opinion changed rapidly.", topic: "society" },
  { ko: "대책", en: "countermeasure", ex: "정부가 새로운 대책을 마련했다.", exEn: "The government prepared new measures.", topic: "society" },
  { ko: "갈등", en: "conflict", ex: "세대 간 갈등이 심해지고 있다.", exEn: "Generational conflict is intensifying.", topic: "society" },
  { ko: "차별", en: "discrimination", ex: "차별 없는 사회를 만들어야 한다.", exEn: "We must build a society without discrimination.", topic: "society" },
  { ko: "시위", en: "protest; demonstration", ex: "수천 명이 시위에 참여했다.", exEn: "Thousands joined the protest.", topic: "society" },
  { ko: "영향", en: "influence; effect", ex: "날씨가 기분에 영향을 미친다.", exEn: "Weather affects one's mood.", topic: "society" },

  // ── Business & work ──
  { ko: "협상", en: "negotiation", ex: "협상이 결렬되었다.", exEn: "The negotiations broke down.", topic: "business" },
  { ko: "계약", en: "contract", ex: "두 회사가 계약을 체결했다.", exEn: "The two companies signed a contract.", topic: "business" },
  { ko: "실적", en: "performance; results", ex: "분기 실적이 예상을 웃돌았다.", exEn: "Quarterly results exceeded expectations.", topic: "business" },
  { ko: "효율", en: "efficiency", ex: "업무 효율을 높여야 한다.", exEn: "We need to raise work efficiency.", topic: "business" },
  { ko: "경쟁력", en: "competitiveness", ex: "가격 경쟁력이 떨어졌다.", exEn: "Price competitiveness has fallen.", topic: "business" },
  { ko: "전략", en: "strategy", ex: "새로운 마케팅 전략이 필요하다.", exEn: "A new marketing strategy is needed.", topic: "business" },
  { ko: "동료", en: "colleague", ex: "동료들과 협력하는 것이 중요하다.", exEn: "Cooperating with colleagues is important.", topic: "business" },
  { ko: "승진", en: "promotion (at work)", ex: "그는 부장으로 승진했다.", exEn: "He was promoted to department head.", topic: "business" },
  { ko: "출장", en: "business trip", ex: "다음 주에 해외 출장을 간다.", exEn: "I'm going on an overseas business trip next week.", topic: "business" },
  { ko: "마감", en: "deadline", ex: "마감이 코앞으로 다가왔다.", exEn: "The deadline is right around the corner.", topic: "business" },

  // ── Emotions & personality ──
  { ko: "불안", en: "anxiety; unease", ex: "미래에 대한 불안을 느낀다.", exEn: "I feel anxiety about the future.", topic: "emotion" },
  { ko: "후회", en: "regret", ex: "그 결정을 후회한다.", exEn: "I regret that decision.", topic: "emotion" },
  { ko: "외로움", en: "loneliness", ex: "도시 생활에서 외로움을 느낄 때가 많다.", exEn: "I often feel lonely in city life.", topic: "emotion" },
  { ko: "자존심", en: "pride; self-esteem", ex: "그는 자존심이 강하다.", exEn: "He has strong pride.", topic: "emotion" },
  { ko: "끈기", en: "perseverance", ex: "성공하려면 끈기가 필요하다.", exEn: "Success requires perseverance.", topic: "emotion" },
  { ko: "배려", en: "consideration; thoughtfulness", ex: "그녀는 배려심이 깊다.", exEn: "She is very considerate.", topic: "emotion" },
  { ko: "솔직하다", en: "to be honest; frank", ex: "솔직하게 말해줘서 고마워.", exEn: "Thanks for being honest.", topic: "emotion" },
  { ko: "소심하다", en: "to be timid", ex: "그는 소심한 성격이다.", exEn: "He has a timid personality.", topic: "emotion" },
  { ko: "부럽다", en: "to be envious of", ex: "네 여유가 부럽다.", exEn: "I envy your composure.", topic: "emotion" },
  { ko: "짜증", en: "irritation; annoyance", ex: "작은 일에도 짜증이 난다.", exEn: "Even small things irritate me.", topic: "emotion" },

  // ── Medical ──
  { ko: "진단", en: "diagnosis", ex: "정확한 진단이 중요하다.", exEn: "An accurate diagnosis is important.", topic: "medical" },
  { ko: "증상", en: "symptom", ex: "어떤 증상이 있나요?", exEn: "What symptoms do you have?", topic: "medical" },
  { ko: "치료", en: "treatment", ex: "조기 치료가 필요하다.", exEn: "Early treatment is necessary.", topic: "medical" },
  { ko: "처방", en: "prescription", ex: "의사가 약을 처방했다.", exEn: "The doctor prescribed medicine.", topic: "medical" },
  { ko: "면역", en: "immunity", ex: "면역 체계가 약해졌다.", exEn: "The immune system has weakened.", topic: "medical" },
  { ko: "감염", en: "infection", ex: "감염을 예방해야 한다.", exEn: "Infection must be prevented.", topic: "medical" },
  { ko: "수술", en: "surgery; operation", ex: "그는 수술을 받았다.", exEn: "He underwent surgery.", topic: "medical" },
  { ko: "부작용", en: "side effect", ex: "이 약은 부작용이 적다.", exEn: "This drug has few side effects.", topic: "medical" },
  { ko: "회복", en: "recovery", ex: "빠른 회복을 빕니다.", exEn: "I wish you a speedy recovery.", topic: "medical" },
  { ko: "예방", en: "prevention", ex: "예방이 치료보다 낫다.", exEn: "Prevention is better than cure.", topic: "medical" },

  // ── Financial ──
  { ko: "투자", en: "investment", ex: "부동산에 투자했다.", exEn: "I invested in real estate.", topic: "finance" },
  { ko: "수익", en: "profit; return", ex: "높은 수익을 기대한다.", exEn: "I expect high returns.", topic: "finance" },
  { ko: "손실", en: "loss", ex: "큰 손실을 입었다.", exEn: "I suffered a big loss.", topic: "finance" },
  { ko: "자산", en: "asset(s)", ex: "그의 자산이 늘어났다.", exEn: "His assets increased.", topic: "finance" },
  { ko: "부채", en: "debt; liabilities", ex: "가계 부채가 사상 최고치를 기록했다.", exEn: "Household debt hit a record high.", topic: "finance" },
  { ko: "물가", en: "prices; cost of living", ex: "물가가 계속 오르고 있다.", exEn: "Prices keep rising.", topic: "finance" },
  { ko: "금리", en: "interest rate", ex: "금리가 인상되었다.", exEn: "Interest rates were raised.", topic: "finance" },
  { ko: "환율", en: "exchange rate", ex: "환율 변동이 심하다.", exEn: "Exchange-rate fluctuations are severe.", topic: "finance" },
  { ko: "예산", en: "budget", ex: "예산을 초과했다.", exEn: "We exceeded the budget.", topic: "finance" },
  { ko: "자금", en: "funds; capital", ex: "사업 자금이 부족하다.", exEn: "We're short on business funds.", topic: "finance" },

  // ── Economic ──
  { ko: "경기", en: "the economy; business conditions", ex: "경기가 침체되어 있다.", exEn: "The economy is in a slump.", topic: "economy" },
  { ko: "침체", en: "stagnation; recession", ex: "경제 침체가 길어지고 있다.", exEn: "The economic recession is dragging on.", topic: "economy" },
  { ko: "성장", en: "growth", ex: "경제 성장이 둔화되었다.", exEn: "Economic growth has slowed.", topic: "economy" },
  { ko: "수요", en: "demand", ex: "수요가 공급을 초과했다.", exEn: "Demand exceeded supply.", topic: "economy" },
  { ko: "공급", en: "supply", ex: "공급이 부족해 가격이 올랐다.", exEn: "Prices rose due to short supply.", topic: "economy" },
  { ko: "수출", en: "export(s)", ex: "수출이 회복세를 보였다.", exEn: "Exports showed signs of recovery.", topic: "economy" },
  { ko: "수입", en: "import(s)", ex: "원유 수입이 늘었다.", exEn: "Crude-oil imports increased.", topic: "economy" },
  { ko: "고용", en: "employment", ex: "고용 시장이 얼어붙었다.", exEn: "The job market froze up.", topic: "economy" },

  // ── Government ──
  { ko: "정책", en: "policy", ex: "새 정책이 발표되었다.", exEn: "A new policy was announced.", topic: "government" },
  { ko: "규제", en: "regulation", ex: "정부가 규제를 강화했다.", exEn: "The government tightened regulations.", topic: "government" },
  { ko: "세금", en: "tax", ex: "세금을 납부해야 한다.", exEn: "Taxes must be paid.", topic: "government" },
  { ko: "보조금", en: "subsidy", ex: "정부가 보조금을 지급한다.", exEn: "The government provides subsidies.", topic: "government" },
  { ko: "복지", en: "welfare", ex: "복지 제도를 확대해야 한다.", exEn: "The welfare system should be expanded.", topic: "government" },
  { ko: "법안", en: "bill (legislation)", ex: "법안이 국회를 통과했다.", exEn: "The bill passed the National Assembly.", topic: "government" },
  { ko: "선거", en: "election", ex: "다음 달에 선거가 있다.", exEn: "There's an election next month.", topic: "government" },
  { ko: "정권", en: "regime; administration", ex: "새 정권이 출범했다.", exEn: "A new administration took office.", topic: "government" },
  { ko: "국회", en: "National Assembly; parliament", ex: "국회에서 토론이 벌어졌다.", exEn: "A debate broke out in the National Assembly.", topic: "government" },
  { ko: "개혁", en: "reform", ex: "교육 개혁이 시급하다.", exEn: "Education reform is urgent.", topic: "government" },
  { ko: "시행", en: "implementation; enforcement", ex: "새 법이 시행되었다.", exEn: "The new law took effect.", topic: "government" },
  { ko: "공무원", en: "civil servant", ex: "그녀는 공무원이다.", exEn: "She is a civil servant.", topic: "government" },

  // ── General advanced ──
  { ko: "모순", en: "contradiction", ex: "그의 말에는 모순이 있다.", exEn: "There's a contradiction in his words.", topic: "general" },
  { ko: "본질", en: "essence; nature", ex: "문제의 본질을 파악해야 한다.", exEn: "We must grasp the essence of the problem.", topic: "general" },
  { ko: "근거", en: "basis; grounds", ex: "그 주장은 근거가 부족하다.", exEn: "That claim lacks grounds.", topic: "general" },
  { ko: "전제", en: "premise", ex: "잘못된 전제에서 출발했다.", exEn: "It started from a wrong premise.", topic: "general" },
  { ko: "관점", en: "perspective; viewpoint", ex: "다양한 관점에서 봐야 한다.", exEn: "We should look from various perspectives.", topic: "general" },
  { ko: "한계", en: "limit", ex: "인간의 능력에는 한계가 있다.", exEn: "Human ability has limits.", topic: "general" },
  { ko: "잠재력", en: "potential", ex: "그는 잠재력이 크다.", exEn: "He has great potential.", topic: "general" },
  { ko: "타협", en: "compromise", ex: "양측이 타협에 이르렀다.", exEn: "Both sides reached a compromise.", topic: "general" },
  { ko: "신뢰", en: "trust", ex: "신뢰를 쌓는 데는 시간이 걸린다.", exEn: "Building trust takes time.", topic: "general" },
  { ko: "책임", en: "responsibility", ex: "책임을 회피하지 마라.", exEn: "Don't dodge responsibility.", topic: "general" },
  { ko: "의무", en: "duty; obligation", ex: "납세는 국민의 의무다.", exEn: "Paying taxes is a citizen's duty.", topic: "general" },
  { ko: "권리", en: "right (entitlement)", ex: "모든 사람은 권리를 가진다.", exEn: "Everyone has rights.", topic: "general" },

  // ── Verbs (Sino-Korean 하다) ──
  { ko: "도입하다", en: "to introduce; adopt", ex: "회사가 새 시스템을 도입했다.", exEn: "The company adopted a new system.", topic: "verb" },
  { ko: "추진하다", en: "to push forward; promote", ex: "정부가 정책을 강력히 추진한다.", exEn: "The government strongly pushes the policy.", topic: "verb" },
  { ko: "완화하다", en: "to ease; relax", ex: "규제를 완화하기로 했다.", exEn: "They decided to ease the regulations.", topic: "verb" },
  { ko: "강화하다", en: "to strengthen; reinforce", ex: "보안을 강화해야 한다.", exEn: "Security must be strengthened.", topic: "verb" },
  { ko: "시행하다", en: "to implement; enforce", ex: "새 제도를 시행한다.", exEn: "They implement the new system.", topic: "verb" },
  { ko: "도출하다", en: "to draw; derive (a conclusion)", ex: "결론을 도출했다.", exEn: "They drew a conclusion.", topic: "verb" },
  { ko: "반영하다", en: "to reflect; incorporate", ex: "의견을 정책에 반영했다.", exEn: "They reflected the opinions in the policy.", topic: "verb" },
  { ko: "제기하다", en: "to raise (an issue/objection)", ex: "그는 의문을 제기했다.", exEn: "He raised a question.", topic: "verb" },
  { ko: "초래하다", en: "to cause; bring about", ex: "부주의가 사고를 초래했다.", exEn: "Carelessness caused the accident.", topic: "verb" },
  { ko: "유발하다", en: "to trigger; induce", ex: "스트레스가 병을 유발한다.", exEn: "Stress induces illness.", topic: "verb" },
  { ko: "모색하다", en: "to seek; explore (a way)", ex: "해결책을 모색하고 있다.", exEn: "They are exploring a solution.", topic: "verb" },
  { ko: "촉진하다", en: "to promote; accelerate", ex: "성장을 촉진한다.", exEn: "It promotes growth.", topic: "verb" },
  { ko: "억제하다", en: "to suppress; curb", ex: "물가 상승을 억제했다.", exEn: "They curbed the price rise.", topic: "verb" },
  { ko: "우려하다", en: "to be concerned; worry", ex: "전문가들이 부작용을 우려한다.", exEn: "Experts worry about side effects.", topic: "verb" },
  { ko: "지적하다", en: "to point out", ex: "문제점을 지적했다.", exEn: "He pointed out the problem.", topic: "verb" },
  { ko: "입증하다", en: "to prove; demonstrate", ex: "그는 결백을 입증했다.", exEn: "He proved his innocence.", topic: "verb" },
  { ko: "추정하다", en: "to estimate; presume", ex: "피해액을 추정했다.", exEn: "They estimated the damage.", topic: "verb" },
  { ko: "분석하다", en: "to analyze", ex: "데이터를 분석했다.", exEn: "They analyzed the data.", topic: "verb" },
  { ko: "평가하다", en: "to evaluate; assess", ex: "성과를 평가한다.", exEn: "They evaluate the results.", topic: "verb" },
  { ko: "검토하다", en: "to review; examine", ex: "제안을 검토 중이다.", exEn: "They are reviewing the proposal.", topic: "verb" },
  { ko: "보장하다", en: "to guarantee; ensure", ex: "권리를 보장한다.", exEn: "It guarantees rights.", topic: "verb" },
  { ko: "확보하다", en: "to secure; obtain", ex: "예산을 확보했다.", exEn: "They secured the budget.", topic: "verb" },
  { ko: "축소하다", en: "to reduce; downsize", ex: "사업을 축소했다.", exEn: "They downsized the business.", topic: "verb" },
  { ko: "확대하다", en: "to expand", ex: "시장을 확대한다.", exEn: "They expand the market.", topic: "verb" },
  { ko: "대응하다", en: "to respond; cope with", ex: "위기에 신속히 대응했다.", exEn: "They responded to the crisis quickly.", topic: "verb" },

  // ── Verbs (native) ──
  { ko: "망설이다", en: "to hesitate", ex: "그는 대답을 망설였다.", exEn: "He hesitated to answer.", topic: "verb" },
  { ko: "깨닫다", en: "to realize", ex: "실수를 깨달았다.", exEn: "I realized my mistake.", topic: "verb" },
  { ko: "견디다", en: "to endure; withstand", ex: "고통을 견뎠다.", exEn: "I endured the pain.", topic: "verb" },
  { ko: "미루다", en: "to postpone; put off", ex: "일을 자꾸 미룬다.", exEn: "I keep putting off work.", topic: "verb" },
  { ko: "떠올리다", en: "to recall; bring to mind", ex: "옛 기억을 떠올렸다.", exEn: "I recalled an old memory.", topic: "verb" },
  { ko: "챙기다", en: "to take care of; pack", ex: "짐을 잘 챙겨라.", exEn: "Pack your things well.", topic: "verb" },
  { ko: "다루다", en: "to handle; deal with", ex: "그 주제를 깊이 다루었다.", exEn: "They dealt with that topic in depth.", topic: "verb" },
  { ko: "이루다", en: "to achieve; form", ex: "마침내 꿈을 이루었다.", exEn: "I finally achieved my dream.", topic: "verb" },
  { ko: "늘리다", en: "to increase (something)", ex: "생산량을 늘렸다.", exEn: "They increased output.", topic: "verb" },
  { ko: "줄이다", en: "to reduce (something)", ex: "비용을 줄였다.", exEn: "They cut costs.", topic: "verb" },
  { ko: "막다", en: "to block; prevent", ex: "사고를 막았다.", exEn: "They prevented the accident.", topic: "verb" },
  { ko: "따지다", en: "to scrutinize; argue over", ex: "손익을 꼼꼼히 따져 봤다.", exEn: "I weighed the pros and cons carefully.", topic: "verb" },
  { ko: "꺼리다", en: "to be reluctant; avoid", ex: "그는 대화를 꺼린다.", exEn: "He avoids conversation.", topic: "verb" },
  { ko: "비롯되다", en: "to originate from; stem from", ex: "문제는 오해에서 비롯됐다.", exEn: "The problem stemmed from a misunderstanding.", topic: "verb" },
  { ko: "마련하다", en: "to prepare; arrange", ex: "대책을 마련했다.", exEn: "They prepared countermeasures.", topic: "verb" },
  { ko: "부추기다", en: "to incite; instigate", ex: "그는 갈등을 부추겼다.", exEn: "He stirred up the conflict.", topic: "verb" },
  { ko: "무릅쓰다", en: "to brave; risk", ex: "위험을 무릅썼다.", exEn: "He braved the danger.", topic: "verb" },
  { ko: "휘말리다", en: "to get caught up in", ex: "사건에 휘말렸다.", exEn: "He got caught up in the incident.", topic: "verb" },
  { ko: "뒤집다", en: "to overturn; flip", ex: "법원이 판결을 뒤집었다.", exEn: "The court overturned the ruling.", topic: "verb" },
  { ko: "무너지다", en: "to collapse", ex: "건물이 무너졌다.", exEn: "The building collapsed.", topic: "verb" },

  // ── Adjectives ──
  { ko: "모호하다", en: "vague; ambiguous", ex: "그의 답변은 모호했다.", exEn: "His answer was vague.", topic: "adjective" },
  { ko: "치밀하다", en: "meticulous; elaborate", ex: "계획이 치밀하다.", exEn: "The plan is meticulous.", topic: "adjective" },
  { ko: "막연하다", en: "vague; uncertain", ex: "막연한 불안감이 든다.", exEn: "I feel a vague anxiety.", topic: "adjective" },
  { ko: "사소하다", en: "trivial; minor", ex: "사소한 일로 다퉜다.", exEn: "We quarreled over a trivial thing.", topic: "adjective" },
  { ko: "엄격하다", en: "strict", ex: "규칙이 엄격하다.", exEn: "The rules are strict.", topic: "adjective" },
  { ko: "뚜렷하다", en: "clear; distinct", ex: "효과가 뚜렷하다.", exEn: "The effect is clear.", topic: "adjective" },
  { ko: "미묘하다", en: "subtle; delicate", ex: "분위기가 미묘했다.", exEn: "The mood was subtle.", topic: "adjective" },
  { ko: "적절하다", en: "appropriate", ex: "적절한 조치를 취했다.", exEn: "They took appropriate action.", topic: "adjective" },
  { ko: "부적절하다", en: "inappropriate", ex: "부적절한 발언이었다.", exEn: "It was an inappropriate remark.", topic: "adjective" },
  { ko: "심각하다", en: "serious; severe", ex: "상황이 심각하다.", exEn: "The situation is serious.", topic: "adjective" },
  { ko: "명확하다", en: "clear; definite", ex: "기준이 명확하다.", exEn: "The criteria are clear.", topic: "adjective" },
  { ko: "복잡하다", en: "complicated", ex: "절차가 복잡하다.", exEn: "The procedure is complicated.", topic: "adjective" },
  { ko: "활발하다", en: "lively; active", ex: "토론이 활발하다.", exEn: "The discussion is lively.", topic: "adjective" },
  { ko: "신중하다", en: "cautious; prudent", ex: "신중하게 결정했다.", exEn: "I decided cautiously.", topic: "adjective" },
  { ko: "과감하다", en: "bold; drastic", ex: "과감한 결정을 내렸다.", exEn: "He made a bold decision.", topic: "adjective" },
  { ko: "무모하다", en: "reckless", ex: "무모한 도전이었다.", exEn: "It was a reckless attempt.", topic: "adjective" },
  { ko: "까다롭다", en: "picky; demanding; tricky", ex: "조건이 까다롭다.", exEn: "The conditions are demanding.", topic: "adjective" },
  { ko: "흔하다", en: "common; frequent", ex: "흔한 실수다.", exEn: "It's a common mistake.", topic: "adjective" },
  { ko: "드물다", en: "rare", ex: "그런 경우는 드물다.", exEn: "Such cases are rare.", topic: "adjective" },
  { ko: "풍부하다", en: "abundant; rich", ex: "경험이 풍부하다.", exEn: "He has abundant experience.", topic: "adjective" },
  { ko: "부족하다", en: "insufficient; lacking", ex: "자료가 부족하다.", exEn: "The data is insufficient.", topic: "adjective" },
  { ko: "유리하다", en: "advantageous", ex: "우리에게 유리하다.", exEn: "It's advantageous to us.", topic: "adjective" },
  { ko: "불리하다", en: "disadvantageous", ex: "상황이 불리하다.", exEn: "The situation is unfavorable.", topic: "adjective" },
  { ko: "타당하다", en: "valid; reasonable", ex: "그 주장은 타당하다.", exEn: "That argument is valid.", topic: "adjective" },
  { ko: "모순되다", en: "to be contradictory", ex: "두 진술이 서로 모순된다.", exEn: "The two statements contradict each other.", topic: "adjective" },
  { ko: "절박하다", en: "desperate; urgent", ex: "상황이 절박하다.", exEn: "The situation is desperate.", topic: "adjective" },
  { ko: "엉뚱하다", en: "absurd; out of place", ex: "엉뚱한 대답을 했다.", exEn: "He gave an off-the-wall answer.", topic: "adjective" },
  { ko: "냉정하다", en: "cool-headed; cold", ex: "냉정하게 판단해라.", exEn: "Judge it calmly.", topic: "adjective" },
  { ko: "답답하다", en: "frustrating; stifling", ex: "상황이 답답하다.", exEn: "The situation is frustrating.", topic: "adjective" },
  { ko: "꾸준하다", en: "steady; consistent", ex: "꾸준한 노력이 중요하다.", exEn: "Consistent effort matters.", topic: "adjective" },

  // ── Idioms (사자성어) ──
  { ko: "유비무환", en: "be prepared, have no worries", ex: "유비무환의 자세가 필요하다.", exEn: "We need a 'be-prepared' attitude.", topic: "idiom" },
  { ko: "일석이조", en: "killing two birds with one stone", ex: "운동은 일석이조의 효과가 있다.", exEn: "Exercise has a two-birds-one-stone effect.", topic: "idiom" },
  { ko: "작심삼일", en: "a resolve that lasts only 3 days", ex: "내 다이어트는 늘 작심삼일이다.", exEn: "My diet resolutions never last.", topic: "idiom" },
  { ko: "자업자득", en: "reaping what you sow", ex: "그건 자업자득이다.", exEn: "That's what he brought on himself.", topic: "idiom" },
  { ko: "천차만별", en: "all different; infinite variety", ex: "제품 가격이 천차만별이다.", exEn: "Product prices vary wildly.", topic: "idiom" },
  { ko: "새옹지마", en: "fortune is unpredictable", ex: "인생은 새옹지마다.", exEn: "Life is unpredictable.", topic: "idiom" },
  { ko: "우왕좌왕", en: "scrambling in confusion", ex: "사람들이 우왕좌왕했다.", exEn: "People scrambled in confusion.", topic: "idiom" },
  { ko: "고진감래", en: "hardship now, reward later", ex: "고진감래라 믿고 버틴다.", exEn: "I endure, trusting hardship brings reward.", topic: "idiom" },
  { ko: "동고동락", en: "sharing joys and sorrows", ex: "우리는 동고동락한 사이다.", exEn: "We've been through thick and thin together.", topic: "idiom" },
  { ko: "과유불급", en: "too much is as bad as too little", ex: "과유불급을 명심해라.", exEn: "Remember: excess is as bad as deficiency.", topic: "idiom" },
  { ko: "역지사지", en: "putting yourself in another's shoes", ex: "역지사지로 생각해 봐.", exEn: "Think from the other person's perspective.", topic: "idiom" },
  { ko: "설상가상", en: "misfortune on top of misfortune", ex: "설상가상으로 비까지 내렸다.", exEn: "To make matters worse, it even rained.", topic: "idiom" },
  { ko: "금상첨화", en: "icing on the cake", ex: "금상첨화의 결과다.", exEn: "It's the cherry on top.", topic: "idiom" },
  { ko: "일사천리", en: "proceeding swiftly and smoothly", ex: "일이 일사천리로 진행됐다.", exEn: "Things proceeded swiftly.", topic: "idiom" },
  { ko: "막상막하", en: "neck and neck; evenly matched", ex: "두 팀 실력이 막상막하다.", exEn: "The two teams are evenly matched.", topic: "idiom" },
  { ko: "십중팔구", en: "in all likelihood (8-9 of 10)", ex: "십중팔구 그럴 것이다.", exEn: "Most likely it'll turn out that way.", topic: "idiom" },
  { ko: "우유부단", en: "indecisive", ex: "그는 우유부단한 성격이다.", exEn: "He has an indecisive personality.", topic: "idiom" },
  { ko: "비일비재", en: "happening all the time; common", ex: "그런 일은 비일비재하다.", exEn: "Such things happen all the time.", topic: "idiom" },
  { ko: "전전긍긍", en: "fretting; on edge", ex: "결과를 두고 전전긍긍했다.", exEn: "He fretted over the result.", topic: "idiom" },
  { ko: "심사숙고", en: "careful deliberation", ex: "심사숙고 끝에 결정했다.", exEn: "I decided after careful deliberation.", topic: "idiom" },

  // ── Law & crime ──
  { ko: "수사", en: "(criminal) investigation", ex: "경찰이 수사를 시작했다.", exEn: "Police began the investigation.", topic: "law" },
  { ko: "기소", en: "indictment; prosecution", ex: "검찰이 그를 기소했다.", exEn: "Prosecutors indicted him.", topic: "law" },
  { ko: "판결", en: "ruling; verdict", ex: "법원이 판결을 내렸다.", exEn: "The court issued a ruling.", topic: "law" },
  { ko: "처벌", en: "punishment", ex: "엄중한 처벌을 받았다.", exEn: "He received a severe punishment.", topic: "law" },
  { ko: "소송", en: "lawsuit", ex: "그는 소송을 제기했다.", exEn: "He filed a lawsuit.", topic: "law" },
  { ko: "변호사", en: "lawyer", ex: "그는 변호사를 선임했다.", exEn: "He hired a lawyer.", topic: "law" },
  { ko: "검찰", en: "the prosecution (office)", ex: "검찰이 수사 중이다.", exEn: "The prosecution is investigating.", topic: "law" },
  { ko: "증거", en: "evidence", ex: "결정적 증거가 나왔다.", exEn: "Decisive evidence emerged.", topic: "law" },
  { ko: "혐의", en: "(criminal) charge; suspicion", ex: "그는 뇌물 혐의를 받고 있다.", exEn: "He faces bribery charges.", topic: "law" },
  { ko: "유죄", en: "guilty", ex: "법원은 유죄를 선고했다.", exEn: "The court found him guilty.", topic: "law" },
  { ko: "무죄", en: "not guilty; innocent", ex: "그는 무죄로 풀려났다.", exEn: "He was acquitted.", topic: "law" },
  { ko: "구속", en: "detention; custody", ex: "그는 구속되었다.", exEn: "He was taken into custody.", topic: "law" },
  { ko: "체포", en: "arrest", ex: "용의자가 체포됐다.", exEn: "The suspect was arrested.", topic: "law" },
  { ko: "용의자", en: "suspect", ex: "경찰이 용의자를 추적 중이다.", exEn: "Police are tracking the suspect.", topic: "law" },
  { ko: "범인", en: "culprit; perpetrator", ex: "마침내 범인을 잡았다.", exEn: "They finally caught the culprit.", topic: "law" },
  { ko: "피해자", en: "victim", ex: "피해자를 보호해야 한다.", exEn: "Victims must be protected.", topic: "law" },
  { ko: "증언", en: "testimony", ex: "그는 법정에서 증언했다.", exEn: "He testified in court.", topic: "law" },
  { ko: "재판", en: "trial", ex: "재판이 진행 중이다.", exEn: "The trial is underway.", topic: "law" },
  { ko: "위반", en: "violation", ex: "이것은 교통 법규 위반이다.", exEn: "This is a traffic-law violation.", topic: "law" },
  { ko: "사기", en: "fraud; scam", ex: "그는 사기를 당했다.", exEn: "He was scammed.", topic: "law" },
  { ko: "뇌물", en: "bribe", ex: "뇌물을 받은 혐의다.", exEn: "He's charged with taking a bribe.", topic: "law" },
  { ko: "횡령", en: "embezzlement", ex: "회사 자금을 횡령했다.", exEn: "He embezzled company funds.", topic: "law" },
  { ko: "구형", en: "sentence demanded by prosecution", ex: "검찰은 징역 5년을 구형했다.", exEn: "Prosecutors sought a 5-year prison term.", topic: "law" },
  { ko: "합의", en: "settlement; agreement", ex: "양측이 합의에 이르렀다.", exEn: "Both sides reached a settlement.", topic: "law" },
  { ko: "고소", en: "(legal) complaint; accusation", ex: "그를 명예훼손으로 고소했다.", exEn: "She filed a defamation complaint against him.", topic: "law" },
  { ko: "벌금", en: "fine (penalty)", ex: "벌금을 부과받았다.", exEn: "He was fined.", topic: "law" },

  // ── Tech / science / environment ──
  { ko: "인공지능", en: "artificial intelligence", ex: "인공지능이 빠르게 발전한다.", exEn: "AI is advancing rapidly.", topic: "tech" },
  { ko: "반도체", en: "semiconductor", ex: "반도체 수출이 늘었다.", exEn: "Semiconductor exports rose.", topic: "tech" },
  { ko: "데이터", en: "data", ex: "방대한 데이터를 분석한다.", exEn: "They analyze vast amounts of data.", topic: "tech" },
  { ko: "알고리즘", en: "algorithm", ex: "추천 알고리즘을 개선했다.", exEn: "They improved the recommendation algorithm.", topic: "tech" },
  { ko: "기후", en: "climate", ex: "기후 변화가 심각하다.", exEn: "Climate change is serious.", topic: "tech" },
  { ko: "탄소", en: "carbon", ex: "탄소 배출을 줄여야 한다.", exEn: "We must cut carbon emissions.", topic: "tech" },
  { ko: "에너지", en: "energy", ex: "재생 에너지가 확대된다.", exEn: "Renewable energy is expanding.", topic: "tech" },
  { ko: "오염", en: "pollution", ex: "대기 오염이 심하다.", exEn: "Air pollution is severe.", topic: "tech" },
  { ko: "자원", en: "resource(s)", ex: "자원이 고갈되고 있다.", exEn: "Resources are running out.", topic: "tech" },
  { ko: "개발", en: "development", ex: "신약 개발에 성공했다.", exEn: "They succeeded in developing a new drug.", topic: "tech" },
  { ko: "실험", en: "experiment", ex: "실험 결과가 나왔다.", exEn: "The experiment results are in.", topic: "tech" },
  { ko: "연구", en: "research", ex: "연구가 활발히 진행된다.", exEn: "Research is actively underway.", topic: "tech" },
  { ko: "기술", en: "technology; skill", ex: "첨단 기술을 보유했다.", exEn: "They hold cutting-edge technology.", topic: "tech" },
  { ko: "장비", en: "equipment", ex: "최신 장비를 도입했다.", exEn: "They introduced the latest equipment.", topic: "tech" },
  { ko: "보안", en: "security (cyber)", ex: "보안이 한층 강화됐다.", exEn: "Security was further strengthened.", topic: "tech" },
  { ko: "위성", en: "satellite", ex: "인공위성을 발사했다.", exEn: "They launched a satellite.", topic: "tech" },
  { ko: "입자", en: "particle", ex: "미세 입자가 검출됐다.", exEn: "Fine particles were detected.", topic: "tech" },
  { ko: "유전자", en: "gene", ex: "유전자 정보를 분석했다.", exEn: "They analyzed the genetic information.", topic: "tech" },
  { ko: "백신", en: "vaccine", ex: "새 백신을 개발했다.", exEn: "They developed a new vaccine.", topic: "tech" },
  { ko: "전기차", en: "electric vehicle", ex: "전기차 보급이 늘었다.", exEn: "EV adoption increased.", topic: "tech" },
  { ko: "배출", en: "emission; discharge", ex: "온실가스 배출이 늘었다.", exEn: "Greenhouse-gas emissions rose.", topic: "tech" },
  { ko: "생태계", en: "ecosystem", ex: "생태계가 파괴됐다.", exEn: "The ecosystem was destroyed.", topic: "tech" },
  { ko: "지속", en: "continuation; persistence", ex: "효과가 오래 지속된다.", exEn: "The effect lasts a long time.", topic: "tech" },
  { ko: "혁신", en: "innovation", ex: "기술 혁신이 필요하다.", exEn: "Technological innovation is needed.", topic: "tech" },
  { ko: "전환", en: "transition; conversion", ex: "친환경 에너지로 전환한다.", exEn: "They are transitioning to green energy.", topic: "tech" },
  { ko: "검증", en: "verification; validation", ex: "안전성 검증이 끝났다.", exEn: "The safety verification is complete.", topic: "tech" },

  // ── Politics & international ──
  { ko: "외교", en: "diplomacy", ex: "외교 관계가 회복됐다.", exEn: "Diplomatic relations recovered.", topic: "politics" },
  { ko: "제재", en: "sanction(s)", ex: "경제 제재를 가했다.", exEn: "They imposed economic sanctions.", topic: "politics" },
  { ko: "동맹", en: "alliance", ex: "두 나라는 오랜 동맹이다.", exEn: "The two countries are longtime allies.", topic: "politics" },
  { ko: "분쟁", en: "dispute; conflict", ex: "국경 분쟁이 계속된다.", exEn: "The border dispute continues.", topic: "politics" },
  { ko: "정상회담", en: "summit (meeting)", ex: "양국 정상회담이 열렸다.", exEn: "A summit between the two nations was held.", topic: "politics" },
  { ko: "협정", en: "agreement; pact", ex: "무역 협정을 맺었다.", exEn: "They signed a trade agreement.", topic: "politics" },
  { ko: "조약", en: "treaty", ex: "평화 조약을 체결했다.", exEn: "They concluded a peace treaty.", topic: "politics" },
  { ko: "외교부", en: "Ministry of Foreign Affairs", ex: "외교부가 성명을 냈다.", exEn: "The foreign ministry issued a statement.", topic: "politics" },
  { ko: "대사", en: "ambassador", ex: "신임 대사가 부임했다.", exEn: "The new ambassador took office.", topic: "politics" },
  { ko: "협력", en: "cooperation", ex: "국제 협력이 필요하다.", exEn: "International cooperation is needed.", topic: "politics" },
  { ko: "긴장", en: "tension", ex: "양국 간 긴장이 고조됐다.", exEn: "Tensions between the two nations rose.", topic: "politics" },
  { ko: "정세", en: "(political) situation", ex: "국제 정세가 불안하다.", exEn: "The international situation is unstable.", topic: "politics" },
  { ko: "난민", en: "refugee", ex: "난민이 급증했다.", exEn: "The number of refugees surged.", topic: "politics" },
  { ko: "이민", en: "immigration", ex: "정부가 이민 정책을 바꿨다.", exEn: "The government changed its immigration policy.", topic: "politics" },
  { ko: "주권", en: "sovereignty", ex: "국가의 주권을 지킨다.", exEn: "They protect national sovereignty.", topic: "politics" },
  { ko: "영토", en: "territory", ex: "영토 분쟁이 일어났다.", exEn: "A territorial dispute broke out.", topic: "politics" },
  { ko: "무역", en: "trade", ex: "무역 적자가 늘었다.", exEn: "The trade deficit grew.", topic: "politics" },
  { ko: "관세", en: "tariff", ex: "수입품에 관세를 인상했다.", exEn: "They raised tariffs on imports.", topic: "politics" },
  { ko: "안보", en: "(national) security", ex: "국가 안보가 위협받고 있다.", exEn: "National security is under threat.", topic: "politics" },
  { ko: "군사", en: "military (affairs)", ex: "군사 훈련을 실시했다.", exEn: "They conducted military drills.", topic: "politics" },
  { ko: "핵", en: "nuclear", ex: "핵 위협이 커졌다.", exEn: "The nuclear threat grew.", topic: "politics" },
  { ko: "평화", en: "peace", ex: "평화를 유지해야 한다.", exEn: "Peace must be maintained.", topic: "politics" },
  { ko: "지지율", en: "approval rating", ex: "대통령의 지지율이 떨어졌다.", exEn: "The president's approval rating fell.", topic: "politics" },
  { ko: "여당", en: "ruling party", ex: "여당이 법안을 발의했다.", exEn: "The ruling party proposed the bill.", topic: "politics" },
  { ko: "야당", en: "opposition party", ex: "야당이 강하게 반발했다.", exEn: "The opposition strongly objected.", topic: "politics" },
  { ko: "협의", en: "consultation; discussion", ex: "양측이 협의를 이어갔다.", exEn: "Both sides continued their consultations.", topic: "politics" },

  // ── Education & academic ──
  { ko: "입시", en: "college entrance exams", ex: "입시 경쟁이 치열하다.", exEn: "Entrance-exam competition is fierce.", topic: "education" },
  { ko: "전공", en: "major (field of study)", ex: "그녀의 전공은 경제학이다.", exEn: "Her major is economics.", topic: "education" },
  { ko: "학위", en: "academic degree", ex: "그는 박사 학위를 받았다.", exEn: "He earned a doctoral degree.", topic: "education" },
  { ko: "논문", en: "thesis; paper", ex: "그녀는 논문을 발표했다.", exEn: "She published a paper.", topic: "education" },
  { ko: "개념", en: "concept", ex: "개념을 정확히 이해해라.", exEn: "Understand the concept precisely.", topic: "education" },
  { ko: "기준", en: "standard; criterion", ex: "평가 기준이 명확하다.", exEn: "The evaluation criteria are clear.", topic: "education" },
  { ko: "요인", en: "factor", ex: "여러 요인이 작용했다.", exEn: "Several factors were at play.", topic: "education" },
  { ko: "구조", en: "structure", ex: "사회 구조가 변했다.", exEn: "The social structure has changed.", topic: "education" },
  { ko: "범위", en: "scope; range", ex: "시험 범위가 넓다.", exEn: "The exam scope is broad.", topic: "education" },
  { ko: "이론", en: "theory", ex: "새로운 이론을 제시했다.", exEn: "He proposed a new theory.", topic: "education" },
  { ko: "가설", en: "hypothesis", ex: "가설을 세웠다.", exEn: "They formed a hypothesis.", topic: "education" },
  { ko: "학문", en: "scholarship; academic discipline", ex: "그는 학문에 정진한다.", exEn: "He devotes himself to scholarship.", topic: "education" },
  { ko: "지식", en: "knowledge", ex: "지식을 꾸준히 쌓는다.", exEn: "He steadily accumulates knowledge.", topic: "education" },
  { ko: "능력", en: "ability; capability", ex: "문제 해결 능력이 뛰어나다.", exEn: "His problem-solving ability is excellent.", topic: "education" },
  { ko: "성취", en: "achievement", ex: "학업 성취도가 높다.", exEn: "Academic achievement is high.", topic: "education" },
  { ko: "교육", en: "education", ex: "교육의 질을 높여야 한다.", exEn: "We must raise the quality of education.", topic: "education" },
  { ko: "강의", en: "lecture; (university) course", ex: "그 강의를 수강했다.", exEn: "I took that course.", topic: "education" },
  { ko: "과제", en: "assignment; task", ex: "과제를 제때 제출했다.", exEn: "I submitted the assignment on time.", topic: "education" },
  { ko: "성적", en: "grades; results", ex: "성적이 크게 올랐다.", exEn: "My grades improved a lot.", topic: "education" },
  { ko: "장학금", en: "scholarship (money)", ex: "그는 장학금을 받았다.", exEn: "He received a scholarship.", topic: "education" },
  { ko: "졸업", en: "graduation", ex: "그는 대학을 졸업했다.", exEn: "He graduated from university.", topic: "education" },
  { ko: "학습", en: "learning", ex: "자기주도 학습이 중요하다.", exEn: "Self-directed learning is important.", topic: "education" },
  { ko: "사고력", en: "thinking; reasoning ability", ex: "비판적 사고력을 기른다.", exEn: "They cultivate critical thinking.", topic: "education" },
  { ko: "탐구", en: "inquiry; investigation", ex: "과학적 탐구가 필요하다.", exEn: "Scientific inquiry is needed.", topic: "education" },
  { ko: "통계", en: "statistics", ex: "그는 통계 자료를 인용했다.", exEn: "He cited statistical data.", topic: "education" },
  { ko: "분야", en: "field; area (of study)", ex: "그는 이 분야의 전문가다.", exEn: "He is an expert in this field.", topic: "education" },
];
